remove_trailing_slash:
    path: /{url}
    defaults: { _controller: AppBundle:Redirecting:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]
landing:
    path: /
    defaults: { _controller: AppBundle:Default:index }
element:
    path: /element
    defaults: { _controller: AppBundle:Default:element }
illustration:
    path: /illustration
    defaults: { _controller: AppBundle:Default:illustration }
