remove_trailing_slash:
    path: /{url}
    defaults: { _controller: AppBundle:Redirecting:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]

landing:
    path: /
    defaults: { _controller: AppBundle:Default:index }
illustrations:
    path: /illustrations
    defaults: { _controller: AppBundle:Default:illustrationList }

element:
    path: /element
    defaults: { _controller: AppBundle:Default:element }
illu:
    path: /illu
    defaults: { _controller: AppBundle:Default:illustration }
