remove_trailing_slash:
    path: /{url}
    defaults: { _controller: AppBundle:Redirecting:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]

banniere:
    path: /banniere/{path}
    defaults: { _controller: AppBundle:Default:banniere }
    requirements:
        path: .+
    methods: [GET]

image:
    path: /image/{path}
    defaults: { _controller: AppBundle:Default:image }
    requirements:
        path: .+
    methods: [GET]

miniature:
    path: /miniature/{path}
    defaults: { _controller: AppBundle:Default:miniature }
    requirements:
        path: .+
    methods: [GET]

landing:
    path: /
    defaults: { _controller: AppBundle:Landing:index }

illustrationList:
    path: /illustrations
    defaults: { 
        _controller: AppBundle:List:index,
        location: "/illustrations/",
        canonicalUrl: "/illustrations",
        categoryName: "Illustrations"
      }

mariageList:
    path: /mariages
    defaults: { 
        _controller: AppBundle:List:index,
        location: "/mariages/",
        canonicalUrl: "/mariages",
        categoryName: "Mariages"
      }

element:
    path: /mariages/{collection}/{element}
    defaults: { _controller: AppBundle:Element:index }

collection_mariage:
    path: /mariages/{collection}
    defaults: { _controller: AppBundle:Collection:index }

illutration:
    path: /illustrations/{dir}
    defaults: { _controller: AppBundle:Illustration:index }
