remove_trailing_slash:
    path: /{url}
    defaults:
        _controller: AppBundle:Redirecting:removeTrailingSlash
    requirements:
        url: .*/$
    methods: [GET]

banniere:
    path: /banniere/{path}
    defaults:
        _controller: AppBundle:Default:banniere
    requirements:
        path: .+
    methods: [GET]

image:
    path: /image/{path}
    defaults:
        _controller: AppBundle:Default:image
    requirements:
        path: .+
    methods: [GET]

assets:
    path: /assets/{path}
    defaults:
        _controller: AppBundle:Default:assets
    requirements:
        path: .+
    methods: [GET]

miniature:
    path: /miniature/{path}
    defaults:
        _controller: AppBundle:Default:miniature
    requirements:
        path: .+
    methods: [GET]

landing:
    path: /
    defaults:
      _controller: AppBundle:Landing:index

partners:
    path: /partenaires
    defaults:
        _controller: AppBundle:Partners:index

contact:
    path: /contact
    defaults:
        _controller: AppBundle:Contact:index

cgv:
    path: /cgv
    defaults:
      _controller: AppBundle:CGV:index

frais-de-port:
    path: /frais-de-port
    defaults:
      _controller: AppBundle:FraisDePort:index

send:
    path: /send
    defaults:
        _controller: AppBundle:Contact:send

illutration:
    path: /illustrations/{dir}
    defaults:
        _controller: AppBundle:Illustration:index

illustrationList:
    path: /illustrations
    defaults:
        _controller: AppBundle:List:index
        location: "/illustrations/"
        canonicalUrl: "/illustrations"
        categoryName: "Illustrations"

surMesure:
    path: /sur-mesure/{dir}
    defaults:
        _controller: AppBundle:SurMesure:index

surMesureList:
    path: /sur-mesure
    defaults:
        _controller: AppBundle:List:index
        location: "/sur-mesure/"
        canonicalUrl: "/sur-mesure"
        categoryName: "SurMesure"

element:
    path: /{family}/{category}/{collection}/{element}
    requirements:
        family: .+
        category: .+
        collection: .+
        element: .+
    defaults:
        _controller: AppBundle:Element:index

decoration:
    path: /decorations/{category}/{dir}
    requirements:
        family: decorations
        category: .+
        dir: .+
    defaults:
        _controller: AppBundle:Decoration:index

collection:
    path: /collections/{category}/{collection}
    requirements:
        category: .+
        collection: .+
    defaults:
        _controller: AppBundle:Collection:index

list:
    path: /{family}/{category}
    requirements:
        category: .+
    defaults:
        _controller: AppBundle:List:index

collectionsCategories:
    path: /collections
    defaults:
        _controller: AppBundle:Category:index
        family: collections

decorationsCategories:
    path: /decorations
    defaults:
        _controller: AppBundle:Category:index
        family: decorations
