remove_trailing_slash:
    path: /{url}
    defaults: { _controller: AppBundle:Redirecting:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]

landing:
    path: /
    defaults: { _controller: AppBundle:Default:index }
illustrationList:
    path: /illustrations
    defaults: { _controller: AppBundle:IllustrationList:index }
illutration:
    path: /illustrations/{dir}
    defaults: { _controller: AppBundle:Illustration:index }

element:
    path: /element
    defaults: { _controller: AppBundle:Default:element }
